services:
  postgres:
    image: postgres:16-alpine
    container_name: iitil-hrms-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: iitil_hrms_ats
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d iitil_hrms_ats"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data: