export const permissions = {
  dashboardRead: 'dashboard.read',
  employeeRead: 'employee.read',
  employeeCreate: 'employee.write',
  employeeUpdate: 'employee.write',
  employeeDelete: 'employee.delete',
  employeeWrite: 'employee.write',
  attendanceRead: 'attendance.read',
  attendanceWrite: 'attendance.write',
  leaveRead: 'leave.read',
  leaveWrite: 'leave.write',
  leaveApprove: 'leave.approve',
  jobRead: 'job.read',
  jobWrite: 'job.write',
  applicationRead: 'application.read',
  applicationWrite: 'application.write',
  interviewManage: 'interview.manage',
  rbacManage: 'rbac.manage',
  employeeDirectoryRead: 'employee.directory.read',
  employeeUserManage: 'employee.user.manage'
} as const;
