ALTER TABLE "roles" ADD COLUMN "hierarchyLevel" INTEGER NOT NULL DEFAULT 100;

UPDATE "roles"
SET "hierarchyLevel" = CASE "code"
  WHEN 'SUPER_ADMIN' THEN 10
  WHEN 'PORTAL_ADMIN' THEN 20
  WHEN 'ADMIN' THEN 20
  WHEN 'HR_MANAGER' THEN 30
  WHEN 'HR' THEN 30
  WHEN 'HR_EXECUTIVE' THEN 35
  WHEN 'TEAM_LEAD' THEN 50
  WHEN 'EMPLOYEE' THEN 80
  WHEN 'INTERN' THEN 90
  ELSE 100
END;
