export const endpoints = {
  auth: {
    login: "/auth/login",
    refresh: "/auth/refresh",
    logout: "/auth/logout",
    forgotPassword: "/auth/forgot-password",
    resetPassword: "/auth/reset-password",
    changePassword: "/auth/change-password",
    me: "/auth/me",
  },
  dashboard: {
    stats: "/dashboard/stats",
    activity: "/dashboard/activity",
  },
  notifications: "/notifications",
  people: {
    list: "/people",
    detail: (id: string) => `/people/${id}`,
    filters: "/people/filters",
    bulkImport: "/people/bulk-import",
    bulkImportConfirm: "/people/bulk-import/confirm"
  },
  employeeDirectory: "/employee-directory",
  userManagement: {
    users: "/user-management/users",
  },
  departments: {
    list: '/departments',
    detail: (id: string) => `/departments/${id}`,
    teams: (id: string) => `/departments/${id}/teams`,
    assignEmployee: (id: string) => `/departments/${id}/employees`
  },
  employees: "/employees",
  employeeReportingManagerOptions: '/employees/reporting-manager-options',
  employeeReportingManager: (id: string) => `/employees/${id}/reporting-manager`,
  attendance: "/attendance",
  attendanceToday: "/attendance/today",
  attendanceAnalytics: "/attendance/analytics",
  attendanceRegularizations: "/attendance/regularizations",
  attendanceRegularize: "/attendance/regularize",
  leaveRequests: "/leave/requests",
  leaveApply: "/leave/apply",
  leaveBalance: "/leave/balances",
  leaveCalendarView: "/leave/calendar",
  leaveHolidays: "/calendar/holidays",
  leaveBalances: "/leaves/balances",
  leaveCalendar: "/leaves/calendar",
  leaveTypes: "/leave-types",
  leavePendingApprovals: "/leaves/pending-approvals",
  leaves: "/leaves",
  recruitment: {
    jobs: "/jobs",
    publishedJobs: "/jobs/published",
    candidates: "/candidates",
    candidateDetail: (id: string) => `/candidates/${id}/detail`,
    candidateActivity: (id: string) => `/candidates/${id}/activity`,
    candidateStage: (id: string) => `/candidates/${id}/stage`,
    candidateNotes: (id: string) => `/candidates/${id}/notes`,
    applications: "/applications",
    interviews: "/interviews",
    quickCreate: "/recruitment/quick-create",
  },
  onboarding: {
    config: "/onboarding/config",
    myProgress: "/onboarding/my-progress",
    submit: "/onboarding/submit",
    review: (employeeId: string) => `/onboarding/${employeeId}/review`,
    activate: (employeeId: string) => `/onboarding/${employeeId}/activate`,
    upload: "/onboarding/documents/upload",
  },
  offerLetters: "/offer-letters",
  templates: "/templates",
  roles: "/rbac/roles",
  permissions: "/rbac/permissions",
  permissionMatrix: "/rbac/permission-matrix",
  settings: "/settings",
  activityLogs: "/activity-logs",
  auditLogs: "/audit-logs",
  profile: "/profile",
  config: {
    list: "/config",
    byKey: (key: string) => `/config/${key}`,
  },
} as const;
